 /**
 * @ngdoc module
 * @name sopro.components.{%=ngName%}
 */
angular.module('sopro.components.{%=ngName%}', [
  'material.animations',
  'material.services.compiler'
])
  .directive('{%=ngName%}', [
    '$$rAF',
    {%=ngName%}Directive
  ]);

/**
* @ngdoc directive
* @name {%=ngName%}
* @module sopro.components.{%=ngName%}
*
* @restrict E
*
* @description
* The `<{%=name%}>` directive is a skeleton element generated by grunt.
*
* @usage
* <hljs lang="html">
* <{%=name%} title-hint="Document what this stuff does">
* </{%=name%}>
* </hljs>
*
*/
function {%=ngName%}Directive($$rAF) {
  return {
    restrict: 'E',
    transclude: true,
    scope: {
      titleHint: "@",
    },
    /*
    template:
      '<div class="gruntDefault">' +
        '<div ng-transclude></div>' +
      '</div>',
    */
    templateUrl: '{%=name%}.html'
  };
}